name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./.NET/First.WebAPI/First.WebAPI.sln
    - name: Build
      run: dotnet build ./.NET/First.WebAPI/First.WebAPI.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./.NET/First.WebAPI/First.WebAPI.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./.NET/First.WebAPI/First.WebAPI.sln -c Release --output ./publish
